PRAGMA foreign_keys=ON;
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL COLLATE NOCASE, password_hash TEXT NOT NULL, verified INTEGER NOT NULL DEFAULT 0, demo INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS profiles (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, username TEXT UNIQUE NOT NULL COLLATE NOCASE, display_name TEXT NOT NULL, bio TEXT NOT NULL DEFAULT '', avatar TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS session_expiry ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS auth_tokens (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, purpose TEXT NOT NULL CHECK(purpose IN ('verify','reset')), expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS videos (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, caption TEXT NOT NULL, category TEXT NOT NULL, audio TEXT NOT NULL DEFAULT 'Original sound', video_url TEXT NOT NULL, thumbnail_url TEXT NOT NULL, duration REAL NOT NULL CHECK(duration>0), comments_enabled INTEGER NOT NULL DEFAULT 1, privacy TEXT NOT NULL DEFAULT 'public' CHECK(privacy IN ('public','followers','private')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS videos_creator_date ON videos(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS videos_category_date ON videos(category,created_at DESC);
CREATE TABLE IF NOT EXISTS video_views (id INTEGER PRIMARY KEY, video_id TEXT NOT NULL REFERENCES videos(id) ON DELETE CASCADE, user_id TEXT REFERENCES users(id) ON DELETE SET NULL, watch_seconds REAL NOT NULL DEFAULT 0, completion REAL NOT NULL DEFAULT 0 CHECK(completion BETWEEN 0 AND 1), completed INTEGER NOT NULL DEFAULT 0, rewatches INTEGER NOT NULL DEFAULT 0, skip_seconds REAL NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS views_user_video ON video_views(user_id,video_id);
CREATE INDEX IF NOT EXISTS views_video ON video_views(video_id);
CREATE TABLE IF NOT EXISTS likes (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, video_id TEXT NOT NULL REFERENCES videos(id) ON DELETE CASCADE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,video_id));
CREATE INDEX IF NOT EXISTS likes_video ON likes(video_id);
CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY, video_id TEXT NOT NULL REFERENCES videos(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, parent_id TEXT REFERENCES comments(id) ON DELETE CASCADE, body TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS comments_video_date ON comments(video_id,created_at);
CREATE INDEX IF NOT EXISTS comments_parent ON comments(parent_id);
CREATE TABLE IF NOT EXISTS comment_likes (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, comment_id TEXT NOT NULL REFERENCES comments(id) ON DELETE CASCADE, PRIMARY KEY(user_id,comment_id));
CREATE INDEX IF NOT EXISTS comment_likes_comment ON comment_likes(comment_id);
CREATE TABLE IF NOT EXISTS follows (follower_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, following_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(follower_id,following_id), CHECK(follower_id != following_id));
CREATE INDEX IF NOT EXISTS follows_following ON follows(following_id);
CREATE TABLE IF NOT EXISTS bookmarks (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, video_id TEXT NOT NULL REFERENCES videos(id) ON DELETE CASCADE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,video_id));
CREATE INDEX IF NOT EXISTS bookmarks_video ON bookmarks(video_id);
CREATE TABLE IF NOT EXISTS shares (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, video_id TEXT NOT NULL REFERENCES videos(id) ON DELETE CASCADE, method TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS shares_video ON shares(video_id);
CREATE TABLE IF NOT EXISTS hashtags (id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS video_hashtags (video_id TEXT NOT NULL REFERENCES videos(id) ON DELETE CASCADE, hashtag_id INTEGER NOT NULL REFERENCES hashtags(id) ON DELETE CASCADE, PRIMARY KEY(video_id,hashtag_id));
CREATE INDEX IF NOT EXISTS hashtag_videos ON video_hashtags(hashtag_id,video_id);
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, actor_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, type TEXT NOT NULL, video_id TEXT REFERENCES videos(id) ON DELETE CASCADE, comment_id TEXT REFERENCES comments(id) ON DELETE CASCADE, read_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS notifications_user_date ON notifications(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, sender_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, recipient_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, video_id TEXT REFERENCES videos(id) ON DELETE CASCADE, body TEXT NOT NULL DEFAULT '', read_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS messages_recipient_date ON messages(recipient_id,created_at DESC);
CREATE TABLE IF NOT EXISTS blocks (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, blocked_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, PRIMARY KEY(user_id,blocked_id), CHECK(user_id != blocked_id));
CREATE INDEX IF NOT EXISTS blocks_blocked ON blocks(blocked_id);
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, reporter_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, target_type TEXT NOT NULL CHECK(target_type IN ('video','user','comment')), target_id TEXT NOT NULL, reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','reviewed','removed','dismissed')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS reports_queue ON reports(status,created_at);
CREATE TABLE IF NOT EXISTS analytics_events (id INTEGER PRIMARY KEY, user_id TEXT REFERENCES users(id) ON DELETE SET NULL, video_id TEXT NOT NULL REFERENCES videos(id) ON DELETE CASCADE, event TEXT NOT NULL CHECK(event IN ('view','completed_view','rewatch','skip','like','comment','save','share','follow_after_watch')), value REAL NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS analytics_user_video ON analytics_events(user_id,video_id,created_at);
CREATE INDEX IF NOT EXISTS analytics_event_date ON analytics_events(event,created_at);
